import os
import sys
import math
from snakemake.utils import min_version

min_version("6.0")

SDIR = os.path.realpath(os.path.dirname(srcdir("Snakefile")))
shell.prefix(f"set -eo pipefail;")


#report: "report/workflow.rst"

#specify config file
configfile: "config/config.yaml"
#include common functions
include: rules/common.smk
#get manifest
manifest_df = pd.read_csv(config["manifest"], sep="\t", index_col="sample", dtype=str)



TEMP_DIR = config.pop("tempdir", "temp")
if TEMP_DIR != "temp":
    if os.path.exists("temp"):
        if os.path.islink("temp") and os.path.realpath("temp") == os.path.realpath(
            TEMP_DIR
        ):
            print("The temp dir has already been linked.")
        else:
            sys.exit("temp/ already in use, please move it before running.")
    else:
        shell("ln -s {TEMP_DIR} temp")


rule all:
    input:
       tmp_fastqs = [f"tmp/{sample}_{superpop}.fastq.gz" for sample, superpop in list(zip(manifest_df["sample"] , manifest_df["superpop"])) ]



include: "rules/alignment_rules.smk"